defaults:
  - model: baseline
  - writer: no_gan
  - metrics: no_gan
  - datasets: librispeech
  - dataloader: main
  - _self_

optimizer:
  generator:
    _target_: torch.optim.Adam
    lr: 1e-4
    betas: [0.5, 0.9]
  discriminator:
    _target_: torch.optim.Adam
    lr: 1e-4
    betas: [0.5, 0.9]

lr_scheduler: null

loss_function:
  generator:
    _target_: src.loss.GeneratorLoss
    lambda_rec: 1
    lambda_adv: 0
    lambda_feat: 0
    lambda_commitment: 1
  discriminator:
    _target_: src.loss.DiscriminatorLoss

trainer:
  use_gan: False
  total_steps: 45000
  epoch_len: ${trainer.total_steps}
  log_step: 50
  audio_log_step: 500
  num_audio_log_examples: 3
  eval_step: 500
  eval_max_batches: 200
  final_eval: True
  final_eval_max_batches: -1
  save_step: 5000
  device_tensors: ["audio"]
  resume_from: null
  device: auto
  override: False
  monitor: "max test_STOI"
  early_stop: ${trainer.total_steps}
  save_dir: "saved"
  seed: 1
