_target_: src.logger.CometMLWriter
project_name: "soundstream"
workspace: null
run_name: "soundstream-no-gan"
mode: "online"
loss_names:
  - generator_loss
  - reconstruction_loss
  - commitment_loss
log_checkpoints: False
id_length: 32
